// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXhWv3KiLIrAs9zSlPW6Vme4OKm6VwQUI',
    appId: '1:76346424584:android:d3d3d9ddd6eff8745140bd',
    messagingSenderId: '76346424584',
    projectId: 'spendy-nandh',
    storageBucket: 'spendy-nandh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0ObbVvjUlNut4alIpQYjQcwQGPUE-B74',
    appId: '1:76346424584:ios:27551e1cb0d6b8405140bd',
    messagingSenderId: '76346424584',
    projectId: 'spendy-nandh',
    storageBucket: 'spendy-nandh.firebasestorage.app',
    iosBundleId: 'com.example.spendytracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0ObbVvjUlNut4alIpQYjQcwQGPUE-B74',
    appId: '1:76346424584:ios:27551e1cb0d6b8405140bd',
    messagingSenderId: '76346424584',
    projectId: 'spendy-nandh',
    storageBucket: 'spendy-nandh.firebasestorage.app',
    iosBundleId: 'com.example.spendytracking',
  );
}
